export default [
  "busty",
  "butt fuck",
  "butt plug",
  "buttcheeks",
  "buttfuck",
  "buttfucka",
  "buttfucker",
  "buttmuch",
  "buttmunch",
  "butt-pirate",
  "buttplug",
  "c.0.c.k",
  "c.o.c.k.",
  "c.u.n.t",
  "c0ck",
  "c-0-c-k",
  "c0cksucker",
  "camel toe",
  "cameltoe",
  "camgirl",
  "camslut",
  "camwhore",
  "carpet muncher",
  "carpetmuncher",
  "cawk",
  "chesticle",
  "chi-chi man",
  "chick with a dick",
  "child-fucker",
  "chinc",
  "chincs",
  "chink",
  "chinky",
  "choad",
  "choade",
  "choade",
  "choc ice",
  "chocolate rosebuds",
  "chode",
  "chodes",
  "chota bags",
  "chota bags",
  "cipa",
  "circlejerk",
  "cl1t",
  "cleveland steamer",
  "clit",
  "clit licker",
  "clitface",
  "clitfuck",
  "clitorus",
  "clits",
  "clitty",
  "clitty litter",
  "clover clamps",
  "clunge",
  "clusterfuck",
  "cnut",
  "c-o-c-k",
  "cock pocket",
  "cock snot",
  "cock sucker",
  "cockass",
  "cockbite",
  "cockblock",
  "cockburger",
  "cockeye",
  "cockface",
  "cockfucker",
  "cockhead",
  "cockholster",
  "cockjockey",
  "cockknocker",
  "cockknoker",
  "cocklump",
  "cockmaster",
  "cockmongler",
  "cockmongruel",
  "cockmonkey",
  "cockmunch",
  "cockmuncher",
  "cocknose",
  "cocknugget",
  "cockshit",
  "cocksmith",
  "cocksmoke",
  "cocksmoker",
  "cocksniffer",
  "cocksuck",
  "cocksuck",
  "cocksucked",
  "cocksucked",
  "cocksucker",
  "cock-sucker",
  "cocksuckers",
  "cocksucking",
  "cocksucks",
  "cocksucks",
  "cocksuka",
  "cocksukka",
];
