export default [
  "deepthroat",
  "dendrophilia",
  "dick",
  "dick head",
  "dick hole",
  "dick hole",
  "dick shy",
  "dick shy",
  "dickbag",
  "dickbeaters",
  "dickdipper",
  "dickface",
  "dickflipper",
  "dickfuck",
  "dickfucker",
  "dickhead",
  "dickheads",
  "dickhole",
  "dickish",
  "dick-ish",
  "dickjuice",
  "dickmilk",
  "dickmonger",
  "dickripper",
  "dicks",
  "dicksipper",
  "dickslap",
  "dick-sneeze",
  "dicksucker",
  "dicksucking",
  "dicktickler",
  "dickwad",
  "dickweasel",
  "dickweed",
  "dickwhipper",
  "dickwod",
  "dickzipper",
  "dildo",
  "dildos",
  "diligaf",
  "dingleberries",
  "dingleberry",
  "dipship",
  "dipshit",
  "dirty pillows",
  "dirty sanchez",
  "dlck",
  "dog style",
  "dog-fucker",
  "doggie style",
  "doggiestyle",
  "doggie-style",
  "doggin",
  "dogging",
  "doggy style",
  "doggystyle",
  "doggy-style",
  "dolcett",
  "dominatrix",
  "dommes",
  "donkey punch",
  "donkeypunch",
  "donkeyribber",
  "doochbag",
  "doofus",
  "dookie",
  "doosh",
  "dopey",
  "double dong",
  "double penetration",
  "douch3",
  "douche",
  "douchebag",
  "douchebags",
  "douche-fag",
  "douchewaffle",
  "douchey",
  "dp action",
  "dry hump",
  "dumass",
  "dumb ass",
  "dumbass",
  "dumbasses",
  "dumbcunt",
  "dumbfuck",
  "dumbshit",
  "dumshit",
  "eat a dick",
  "eat a dick",
  "eat hair pie",
  "eat hair pie",
  "eat my ass",
  "ejaculate",
  "ejaculated",
  "ejaculates",
  "ejaculates",
  "ejaculating",
  "ejaculating",
  "ejaculatings",
  "ejaculation",
];
