export default [
  "lezzie",
  "lolita",
  "lovemaking",
  "lube",
  "m0f0",
  "m0fo",
  "m45terbate",
  "ma5terb8",
  "ma5terbate",
  "mafugly",
  "mafugly",
  "make me come",
  "male squirting",
  "masterb8",
  "masterbat*",
  "masterbat3",
  "masterbate",
  "master-bate",
  "master-bate",
  "masterbating",
  "masterbation",
  "masterbations",
  "masturbate",
  "masturbating",
  "masturbation",
  "mcfagget",
  "menage a trois",
  "meth",
  "m-fucking",
  "microphallus",
  "milf",
  "missionary position",
  "mof0",
  "mofo",
  "mo-fo",
  "molest",
  "moolie",
  "moron",
  "mothafuck",
  "mothafucka",
  "mothafuckas",
  "mothafuckaz",
  "mothafucked",
  "mothafucked",
  "mothafucker",
  "mothafuckers",
  "mothafuckin",
  "mothafucking",
  "mothafucking",
  "mothafuckings",
  "mothafucks",
  "mother fucker",
  "mother fucker",
  "motherfuck",
  "motherfucka",
  "motherfucked",
  "motherfucker",
  "motherfuckers",
  "motherfuckin",
  "motherfucking",
  "motherfuckings",
  "motherfuckka",
  "motherfucks",
  "mound of venus",
  "muff diver",
  "muff puff",
  "muff puff",
  "muffdiver",
  "muffdiving",
  "murder",
  "mutha",
  "muthafecker",
  "muthafuckker",
  "muther",
  "mutherfucker",
  "n1gga",
  "n1gger",
  "nambla",
  "nawashi",
  "need the dick",
  "negro",
  "nig nog",
  "nigaboo",
  "nigg3r",
  "nigg4h",
  "nigga",
  "niggah",
  "niggas",
  "niggaz",
  "nigger",
  "niggers",
  "niglet",
  "nig-nog",
  "nimphomania",
  "nob jokey",
  "nobhead",
  "nobjocky",
  "nobjokey",
  "nonce",
  "nsfw images",
];
